from __future__ import annotations

import re
import unicodedata
from typing import Any, Dict, List


SUPPORT_REGISTRY: List[Dict[str, Any]] = [
    {
        "id": "before_you_send",
        "name": "Before You Send",
        "category": "communication_support",
        "description": "Checks a message before sending for tone, clarity, and avoidable friction.",
        "trigger_contexts": ["message", "email", "social", "luxway"],
        "explicit_commands": ["gondermeden kontrol et", "bunu gondermeden kontrol et", "yollamadan bak"],
        "suggested_modes": ["general", "message", "email"],
        "proactive_allowed": True,
        "proactive_threshold": "medium",
        "risk_level": "medium",
        "ui_behavior": "small_inline_hint",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "one_tap_apology_boundary",
        "name": "One Tap Apology / Boundary",
        "category": "communication_support",
        "description": "Offers a short apology or boundary draft without sending it.",
        "trigger_contexts": ["message", "social"],
        "explicit_commands": ["ozur ve sinir yaz", "kisa ozur yaz", "sinir koy"],
        "suggested_modes": ["message", "general"],
        "proactive_allowed": False,
        "proactive_threshold": "high",
        "risk_level": "medium",
        "ui_behavior": "draft_chip",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "do_i_sound_weird",
        "name": "Do I Sound Weird?",
        "category": "social_risk_support",
        "description": "Checks whether wording may sound awkward, harsh, cold, or confusing.",
        "trigger_contexts": ["message", "email", "social"],
        "explicit_commands": ["garip duruyor mu", "tuhaf mi", "kotu mu duyuluyor"],
        "suggested_modes": ["message", "social"],
        "proactive_allowed": True,
        "proactive_threshold": "medium",
        "risk_level": "low",
        "ui_behavior": "one_line_hint",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "excuse_cleaner",
        "name": "Excuse Cleaner",
        "category": "communication_support",
        "description": "Turns a messy excuse into a cleaner, respectful explanation.",
        "trigger_contexts": ["message", "workspace", "email"],
        "explicit_commands": ["bahaneyi temizle", "mazeretimi duzelt", "daha temiz acikla"],
        "suggested_modes": ["message", "workspace"],
        "proactive_allowed": False,
        "proactive_threshold": "medium",
        "risk_level": "low",
        "ui_behavior": "draft_chip",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "awkward_moment_rescue",
        "name": "Awkward Moment Rescue",
        "category": "social_risk_support",
        "description": "Suggests one low-pressure way to recover from an awkward moment.",
        "trigger_contexts": ["social", "message", "general"],
        "explicit_commands": ["garip ani kurtar", "awkward moment rescue", "ortami toparla"],
        "suggested_modes": ["social", "general"],
        "proactive_allowed": True,
        "proactive_threshold": "high",
        "risk_level": "medium",
        "ui_behavior": "single_suggestion",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "tiny_courage",
        "name": "Tiny Courage",
        "category": "energy_support",
        "description": "Offers one tiny next sentence or action when the user is hesitant.",
        "trigger_contexts": ["general", "workspace", "message"],
        "explicit_commands": ["kucuk cesaret ver", "tiny courage", "baslamak icin tek cumle"],
        "suggested_modes": ["general"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "one_step_hint",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "polite_no_generator",
        "name": "Polite No Generator",
        "category": "communication_support",
        "description": "Drafts a polite refusal without sending it.",
        "trigger_contexts": ["message", "email", "social"],
        "explicit_commands": ["nazik hayir yaz", "kibarca hayir de", "reddet ama nazik"],
        "suggested_modes": ["message", "email"],
        "proactive_allowed": False,
        "proactive_threshold": "medium",
        "risk_level": "low",
        "ui_behavior": "draft_chip",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "first_message_builder",
        "name": "First Message Builder",
        "category": "communication_support",
        "description": "Builds a low-pressure first message draft.",
        "trigger_contexts": ["message", "social"],
        "explicit_commands": ["ilk mesaj yaz", "first message", "konusmayi baslat"],
        "suggested_modes": ["message", "social"],
        "proactive_allowed": False,
        "proactive_threshold": "medium",
        "risk_level": "medium",
        "ui_behavior": "draft_chip",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "reply_temperature",
        "name": "Reply Temperature",
        "category": "communication_support",
        "description": "Adjusts reply warmth, distance, softness, or directness.",
        "trigger_contexts": ["message", "email", "social"],
        "explicit_commands": ["cevabin sicakligini ayarla", "daha sicak yap", "daha mesafeli yap"],
        "suggested_modes": ["message", "email"],
        "proactive_allowed": True,
        "proactive_threshold": "medium",
        "risk_level": "low",
        "ui_behavior": "tone_slider_hint",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "regret_filter",
        "name": "Regret Filter",
        "category": "social_risk_support",
        "description": "Flags wording the user may regret later, without moralizing.",
        "trigger_contexts": ["message", "email", "social"],
        "explicit_commands": ["pisman olur muyum", "regret filter", "sonra pisman eder mi"],
        "suggested_modes": ["message", "social"],
        "proactive_allowed": True,
        "proactive_threshold": "medium",
        "risk_level": "medium",
        "ui_behavior": "small_warning",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "social_screenshot_interpreter",
        "name": "Social Screenshot Interpreter",
        "category": "social_risk_support",
        "description": "Preview-only social screenshot interpretation without certainty claims.",
        "trigger_contexts": ["social", "visual"],
        "explicit_commands": ["sosyal ekran goruntusunu yorumla", "screenshot yorumla", "mesaj ekranini oku"],
        "suggested_modes": ["visual", "social"],
        "proactive_allowed": False,
        "proactive_threshold": "high",
        "risk_level": "high",
        "ui_behavior": "careful_preview",
        "requires_permission": True,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "one_breath_summary",
        "name": "One Breath Summary",
        "category": "clarity_support",
        "description": "Compresses something into a one-breath summary.",
        "trigger_contexts": ["general", "workspace", "voice"],
        "explicit_commands": ["tek nefeslik ozet cikar", "one breath summary", "tek nefeste ozetle"],
        "suggested_modes": ["general", "workspace"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "one_line_summary",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "name_this_thing",
        "name": "Name This Thing",
        "category": "naming_support",
        "description": "Suggests a name for an idea, project, feeling, file, or section.",
        "trigger_contexts": ["workspace", "visual", "general"],
        "explicit_commands": ["suna isim bul", "buna isim ver", "name this thing"],
        "suggested_modes": ["workspace", "visual"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "name_options",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "taboo_translator",
        "name": "Taboo Translator",
        "category": "communication_support",
        "description": "Says a difficult thing more gently and clearly without manipulation.",
        "trigger_contexts": ["message", "email", "social"],
        "explicit_commands": ["bunu kirmadan soyle", "taboo translator", "sert olmadan soyle"],
        "suggested_modes": ["message", "social"],
        "proactive_allowed": False,
        "proactive_threshold": "medium",
        "risk_level": "medium",
        "ui_behavior": "draft_chip",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "micro_brief",
        "name": "Micro-Brief",
        "category": "clarity_support",
        "description": "Creates a tiny brief with goal, audience, and next action.",
        "trigger_contexts": ["workspace", "general", "luxway"],
        "explicit_commands": ["micro brief yap", "mikro brief", "kisa brief"],
        "suggested_modes": ["workspace", "general"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "compact_brief",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "energy_safe_plan",
        "name": "Energy-Safe Plan",
        "category": "energy_support",
        "description": "Turns a task into a low-energy, low-friction plan.",
        "trigger_contexts": ["workspace", "general", "voice"],
        "explicit_commands": ["enerjim dusuk kolay plan yap", "energy safe plan", "yormayan plan"],
        "suggested_modes": ["workspace", "general"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "one_step_plan",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "explain_my_taste",
        "name": "Explain My Taste",
        "category": "taste_support",
        "description": "Explains a preference or visual/style taste in plain language.",
        "trigger_contexts": ["visual", "workspace", "general"],
        "explicit_commands": ["zevkimi acikla", "neden bunu seviyorum", "explain my taste"],
        "suggested_modes": ["visual", "general"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "taste_note",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "personal_phrase_bank",
        "name": "Personal Phrase Bank",
        "category": "communication_support",
        "description": "Suggests reusable phrase patterns without saving them.",
        "trigger_contexts": ["message", "email", "workspace"],
        "explicit_commands": ["cumle bankasi", "benim uslubumda kalip", "phrase bank"],
        "suggested_modes": ["message", "workspace"],
        "proactive_allowed": False,
        "proactive_threshold": "medium",
        "risk_level": "medium",
        "ui_behavior": "phrase_options",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "micro_decision",
        "name": "Micro-Decision",
        "category": "decision_support",
        "description": "Helps choose one small next option without over-planning.",
        "trigger_contexts": ["general", "workspace", "luxway"],
        "explicit_commands": ["mikro karar", "micro decision", "hangisini seceyim"],
        "suggested_modes": ["general"],
        "proactive_allowed": True,
        "proactive_threshold": "low",
        "risk_level": "low",
        "ui_behavior": "two_option_hint",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
    {
        "id": "reputation_check",
        "name": "Reputation Check",
        "category": "reputation_support",
        "description": "Checks how a message or action may be perceived without certainty claims.",
        "trigger_contexts": ["message", "social", "email"],
        "explicit_commands": ["bu beni nasil gosteriyor", "reputation check", "nasil algilanirim"],
        "suggested_modes": ["social", "message"],
        "proactive_allowed": True,
        "proactive_threshold": "medium",
        "risk_level": "medium",
        "ui_behavior": "small_risk_note",
        "requires_permission": False,
        "requires_confirmation": False,
        "real_action_enabled": False,
        "read_only": True,
    },
]


SUPPORT_RULES = {
    "before_you_send": ["gondermeden", "yollamadan", "atmadan", "kontrol et"],
    "polite_no_generator": ["nazik hayir", "kibarca hayir", "reddet"],
    "do_i_sound_weird": ["garip duruyor", "tuhaf", "weird", "kotu duyuluyor"],
    "one_breath_summary": ["tek nefes", "one breath", "tek nefeste"],
    "micro_brief": ["micro brief", "mikro brief", "kisa brief"],
    "energy_safe_plan": ["enerjim dusuk", "yormayan plan", "kolay plan"],
    "name_this_thing": ["isim bul", "isim ver", "name this"],
    "reputation_check": ["beni nasil gosteriyor", "nasil algilanirim", "reputation"],
    "taboo_translator": ["kirmadan soyle", "sert olmadan", "taboo"],
    "reply_temperature": ["sicakligini ayarla", "daha sicak", "daha mesafeli"],
}


def _normalize(text: str) -> str:
    value = unicodedata.normalize("NFKD", text or "")
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    value = value.lower().replace("ı", "i").replace("ğ", "g").replace("ş", "s")
    value = value.replace("ö", "o").replace("ü", "u").replace("ç", "c")
    return re.sub(r"\s+", " ", value).strip()


def _find_support(support_id: str) -> Dict[str, Any]:
    for support in SUPPORT_REGISTRY:
        if support["id"] == support_id:
            return support
    return SUPPORT_REGISTRY[0]


def support_registry() -> Dict[str, Any]:
    return {
        "status": "support_registry_ready",
        "support_count": len(SUPPORT_REGISTRY),
        "supports": SUPPORT_REGISTRY,
        "read_only": True,
        "real_action_enabled": False,
        "message_sent": False,
        "data_saved": False,
        "memory_write_performed": False,
        "db_write_performed": False,
    }


def preview_background_support(
    command: str,
    context: str = "",
    source_area: str = "general",
    sensitivity: str = "normal",
) -> Dict[str, Any]:
    haystack = _normalize(f"{command} {context}")
    matches: List[Dict[str, Any]] = []
    for support_id, keywords in SUPPORT_RULES.items():
        matched = [keyword for keyword in keywords if keyword in haystack]
        if matched:
            support = _find_support(support_id)
            matches.append(
                {
                    "id": support["id"],
                    "name": support["name"],
                    "category": support["category"],
                    "matched_keywords": matched,
                    "confidence": "high" if len(matched) > 1 else "medium",
                }
            )
    if not matches:
        matches.append(
            {
                "id": "micro_decision",
                "name": "Micro-Decision",
                "category": "decision_support",
                "matched_keywords": [],
                "confidence": "low",
            }
        )

    recommended = _find_support(matches[0]["id"])
    risk_level = "high" if sensitivity in {"high", "privacy", "safety"} else recommended["risk_level"]
    return {
        "raw_command": command,
        "detected_supports": matches,
        "recommended_support": {
            "id": recommended["id"],
            "name": recommended["name"],
            "category": recommended["category"],
            "ui_behavior": recommended["ui_behavior"],
            "suggested_modes": recommended["suggested_modes"],
        },
        "trigger_reason": "Matched explicit support keywords" if matches[0]["matched_keywords"] else "Low-confidence fallback preview",
        "source_area": source_area,
        "risk_level": risk_level,
        "proactive_allowed": recommended["proactive_allowed"] and risk_level != "high",
        "proactive_threshold": recommended["proactive_threshold"],
        "suggested_user_facing_hint": "I can offer one small read-only suggestion here.",
        "safe_preview_message": "Preview only: no message is sent, no data is saved, and no memory is written.",
        "real_action_enabled": False,
        "action_performed": False,
        "message_sent": False,
        "data_saved": False,
        "memory_write_performed": False,
        "db_write_performed": False,
        "read_only": True,
    }


def support_status() -> Dict[str, Any]:
    return {
        "layer": "21.1",
        "name": "Background Support Intelligence Registry",
        "status": "scaffold_ready",
        "support_count": len(SUPPORT_REGISTRY),
        "categories": sorted({support["category"] for support in SUPPORT_REGISTRY}),
        "read_only": True,
        "real_action_enabled": False,
        "action_performed": False,
        "message_sent": False,
        "data_saved": False,
        "memory_write_performed": False,
        "db_write_performed": False,
        "chat_stream_touched": False,
        "typewriter_runtime_touched": False,
        "safety_notes": [
            "No real send/export/save action is performed.",
            "No raw private message is stored.",
            "Social interpretation avoids certainty claims and manipulation.",
            "Clinical or crisis diagnosis is not performed.",
        ],
    }
